version: "3.7"

services:
  server:
    image: nginx:stable-alpine
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - just-eat
  
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    #   - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: ahsan 
      # MYSQL_PASSWORD: secret 
      MYSQL_DATABASE: just_eat
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/data.sql"
    networks:
      - just-eat
  
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - just-eat

  composer:
    image: composer:2
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - just-eat
  
networks:
  just-eat:
    